"""
Real-time Infrastructure Telemetry Simulator
Simulates thermodynamic and operational relationships:
- Compute load (CPU/GPU) drives power dissipation
- Power dissipation raises temperature
- Cooling counteracts thermal rise; cooling deficit causes sharp thermal spike
- Network load creates compute & memory pressure
- Multi-variate risk score automatically recalculates
"""

import random
from datetime import datetime, timezone
from sqlalchemy.orm import Session
from database import SessionLocal, Server, ServerMetricHistory
from anomaly_engine import anomaly_detector

class TelemetrySimulator:
    def __init__(self):
        self.step_count = 0

    def tick(self, db: Session):
        """
        Executes one physics-correlated simulation cycle across all servers.
        """
        self.step_count += 1
        servers = db.query(Server).all()
        now_str = datetime.now(timezone.utc).strftime("%H:%M:%S")

        for server in servers:
            # Determine profile baseline
            if server.server_id == "DC-SRV-024":
                # Cooling degraded server: high heat, low cooling
                target_cooling = 52.0 + random.uniform(-2.0, 3.0)
                cpu_drift = random.uniform(-1.5, 2.0)
                gpu_drift = random.uniform(-1.0, 1.5)
            elif server.server_id == "DC-SRV-009":
                # Runaway process node: elevated CPU
                target_cooling = 78.0 + random.uniform(-2.0, 2.0)
                cpu_drift = random.uniform(-1.0, 2.5)
                gpu_drift = random.uniform(-2.0, 2.0)
            elif server.server_id == "DC-SRV-017":
                # High-throughput DB: high RAM & network
                target_cooling = 73.0 + random.uniform(-2.0, 2.0)
                cpu_drift = random.uniform(-1.5, 2.0)
                gpu_drift = random.uniform(-1.0, 1.0)
            else:
                # Nominal healthy servers
                target_cooling = 88.0 + random.uniform(-2.0, 4.0)
                cpu_drift = random.uniform(-2.0, 2.0)
                gpu_drift = random.uniform(-2.0, 2.0)

            # Apply controlled drift
            new_cpu = max(15.0, min(99.0, server.cpu + cpu_drift))
            new_gpu = max(5.0, min(98.0, server.gpu + gpu_drift))
            new_ram = max(20.0, min(96.0, server.ram + random.uniform(-0.8, 1.0)))
            new_cooling = max(35.0, min(98.0, target_cooling))
            
            # Network fluctuations
            net_drift = random.uniform(-0.4, 0.4)
            new_network = max(1.2, min(25.0, server.network + net_drift))

            # Power calculation based on compute loads (Base ~ 280W + dynamic component)
            compute_power = (new_cpu * 2.2) + (new_gpu * 2.8) + (new_ram * 0.4)
            new_power = max(250.0, min(850.0, 240.0 + compute_power + random.uniform(-8.0, 8.0)))

            # Thermal calculation:
            # Heat generated by power minus heat rejected by cooling
            heat_generated = (new_power / 10.0) * 0.95
            heat_rejected = (new_cooling / 100.0) * 45.0
            ambient_baseline = 24.0
            raw_temp = ambient_baseline + (heat_generated - heat_rejected) + 12.0
            
            # Smooth transition for temperature
            new_temp = (server.temperature * 0.75) + (raw_temp * 0.25)
            new_temp = round(max(40.0, min(92.0, new_temp)), 1)

            # Water usage proportional to cooling requirement
            new_water = round(max(6.0, min(35.0, (new_power / 28.0) * (1.1 - (new_cooling / 200.0)))), 1)

            # Multi-metric risk evaluation
            analysis = anomaly_detector.calculate_risk_score(
                cpu=new_cpu,
                ram=new_ram,
                gpu=new_gpu,
                temp=new_temp,
                power=new_power,
                cooling=new_cooling
            )

            # Update server state
            server.cpu = round(new_cpu, 1)
            server.ram = round(new_ram, 1)
            server.gpu = round(new_gpu, 1)
            server.temperature = new_temp
            server.network = round(new_network, 1)
            server.power = round(new_power, 1)
            server.cooling = round(new_cooling, 1)
            server.water_usage = new_water
            server.risk_score = analysis["risk_score"]
            server.status = analysis["status"]
            server.last_updated = datetime.now(timezone.utc)

            # Append historical metric every few ticks
            if self.step_count % 3 == 0:
                history_point = ServerMetricHistory(
                    server_id=server.server_id,
                    timestamp=now_str,
                    cpu=server.cpu,
                    ram=server.ram,
                    gpu=server.gpu,
                    temperature=server.temperature,
                    network=server.network,
                    power=server.power,
                    cooling=server.cooling
                )
                db.add(history_point)

        db.commit()

simulator = TelemetrySimulator()
